MvcMusicStore/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcMusicStore.Models;


namespace MvcMusicStore.Controllers
{
    public class AlbumController : Controller
    {
        private readonly MvcMusicStoreContext _context;

        public AlbumController(MvcMusicStoreContext context)
        {
            _context = context;
        }

        // GET: Album
        public async Task<IActionResult> Index()
        {
            var mvcMusicStoreContext = _context.Album.Include(a => a.Artist).Include(a => a.Genre);
            return View(await mvcMusicStoreContext.ToListAsync());
        }

        // GET: Album/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Album
                .Include(a => a.Artist)
                .Include(a => a.Genre)
                .FirstOrDefaultAsync(m => m.AlbumId == id);
            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }

        // GET: Album/Create
        public IActionResult Create()
        {
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "Name");
            ViewData["GenreId"] = new SelectList(_context.Genre, "GenreId", "GenreId");
            return View();
        }

        // POST: Album/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl")] Album album)
        {
            try
            {
                if (string.IsNullOrEmpty(album.Title))
                {
                    ModelState.AddModelError("", "Title is required field");
                    ModelState.AddModelError("Title", "Field Specific - Title is required field");
                }
                if (ModelState.IsValid)
                {
                    //throw new Exception("Database not avialable");
                    // Adding new album in the context object
                    _context.Add(album);
                    // saving in the database
                    await _context.SaveChangesAsync();

                    TempData["message"] = "Album Record added successfully";
                    // redirecting the control back to Index action showing list of all the albums
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.GetBaseException().Message);
                TempData["message"] = ex.GetBaseException().Message;
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "Name", album.ArtistId);
            ViewData["GenreId"] = new SelectList(_context.Genre, "GenreId", "GenreId", album.GenreId);
            return View(album);
        }

        // GET: Album/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Album.FindAsync(id);
            if (album == null)
            {
                return NotFound();
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "Name", album.ArtistId);
            ViewData["GenreId"] = new SelectList(_context.Genre, "GenreId", "GenreId", album.GenreId);
            return View(album);
        }

        // POST: Album/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl")] Album album)
        {
            if (id != album.AlbumId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(album);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlbumExists(album.AlbumId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "Name", album.ArtistId);
            ViewData["GenreId"] = new SelectList(_context.Genre, "GenreId", "GenreId", album.GenreId);
            return View(album);
        }

        // GET: Album/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Album
                .Include(a => a.Artist)
                .Include(a => a.Genre)
                .FirstOrDefaultAsync(m => m.AlbumId == id);
            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }

        // POST: Album/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var album = await _context.Album.FindAsync(id);
            _context.Album.Remove(album);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AlbumExists(int id)
        {
            return _context.Album.Any(e => e.AlbumId == id);
        }

        public IActionResult LINQtest()
        {
            try
            {
                var albums = from anAlbum in _context.Album
                             join anArtist in _context.Artist on anAlbum.ArtistId equals anArtist.ArtistId
                             join aGenre in _context.Genre on anAlbum.GenreId equals aGenre.GenreId
                             select new Album
                             {
                                 AlbumId = anAlbum.AlbumId,
                                 Title = anAlbum.Title,
                                 ArtistId = anAlbum.ArtistId,
                                 GenreId = anAlbum.GenreId,
                                 AlbumArtUrl = anAlbum.AlbumArtUrl,
                                 Artist = anArtist,
                                 Genre = aGenre
                             };

                return View(albums);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "exception getting Albums:" + ex.GetBaseException().Message);
                return View(new List<Album>());
            }

        }

        public IActionResult EFtest()
        {
            try
            {
                //var albums = _context.Album.Include(a => a.Artist).Include(b => b.Genre)
                //    .Where(a=>a.Title.Contains("disc") && a.Artist.Name == "Deep Purple ");

                //var albums = _context.Album.Include(a => a.Artist).Include(b => b.Genre)
                //    .OrderBy(a => a.Artist.Name).ThenBy(a => a.Title);

                var albums = _context.Album.Include(a => a.Artist).Include(b => b.Genre)
                    .Skip(10).Take(10);

                return View("LINQtest", albums);
            }
            catch (Exception ex)
            {
                while (ex.InnerException != null) ex = ex.InnerException;
                ModelState.AddModelError("", "exception getting Albums: " + ex.Message);
                return View(new List<Album>());
            }
        }

        public IActionResult LINQtest2()
        {

            var albums = from record in _context.Album.Include(a => a.Artist)
                         select new PriceSurcharged
                         {
                             Title = record.Title,
                             Artist = record.Artist.Name,
                             SurChargedPrice = record.Price * (1 + .13),
                             Price = record.Price
                         };
            return View(albums);
        }

        public IActionResult GroupBytest()
        {

            var artistCount = from fred in _context.Album
                              group fred by new
                              {
                                  fred.ArtistId,
                                  fred.Artist.Name
                              } into condensedFred
                              select new LinqTestArtistCount
                              {
                                  artist = condensedFred.Key.Name,
                                  count = condensedFred.Count(),
                                  totalPrice = condensedFred.Sum(a => a.Price),
                                  averagePrice = condensedFred.Average(a => a.Price)
                              };
            return View(artistCount.OrderByDescending(a => a.count));
        }

        public ActionResult Search(string query)
        {
            var albums = _context.Album.Include(a => a.Artist)
                .Where(a => a.Title.Contains(query) || a.Artist.Name.Contains(query));
            return View(albums);
        }

    }
}

MvcMusicStore/Views/Shared/BaseSite.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
</head>
<body>
    <h1>@ViewBag.Title</h1>
    <div id="main-content">@RenderBody()</div>
    @if (IsSectionDefined("Footer"))
    {
        RenderSection("Footer");
    }
    else
    {
        <span>This is the default footer</span>
    }

</body>
</html>

MvcMusicStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcMusicStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcMusicStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Album" asp-action="Create">Album</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="RequestStuff">RequestStuff</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Album" asp-action="EFtest">LINQtest</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Album" asp-action="LINQtest2">LINQtest2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Album" asp-action="GroupBytest">GroupBytest</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <form asp-controller="Album" asp-action="Search" method="post">
            <input type="text" name="query" />
            <input type="submit" name="Search" value="Search" />
        </form>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @TempData["message"]
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MvcMusicStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>